version: '3.4'
services:
  mysql_container:
    image: mysql:latest
    ports:
      - 3306:3306
    environment:
      MYSQL_ROOT_PASSWORD: password
      MYSQL_DATABASE: era5_dataset
      MYSQL_PASSWORD: password
    volumes:
      - /mysql_data.tar